### ISSUE TITLE
Email checker

### ISSUE THREAD

**Issue by kongclarius** [wahyuandhika/YahooCloning#4]
Email checker nya gabisa sob ,status not vuln padahal saya cek manual ada yang vuln.

**Comment by wahyuandhika** [comment]
oh ya? terima kasih, nanti akan saya perbaiki.

Pada tanggal Sen, 15 Jul 2019 12.20, kongclarius <notifications@github.com>
menulis:

**Comment by wahyuandhika** [comment]
udah di perbaiki bro, coba cek lagi bisa ga...

**Comment by kongclarius** [comment]
Memang paling mantap, sukses terus bro
